zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka_1:
  build: .
  ports:
    - "9091:9092"
  links: 
    - zookeeper:zk
  environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ADVERTISED_PORT: "9092"
  volumes:
    - /kafka_1:/kafka
kafka_2:
  build: .
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ADVERTISED_PORT: "9092"
  volumes:
    - /kafka_2:/kafka
kafka_3:
  build: .
  ports:
    - "9093:9092"
  links: 
    - zookeeper:zk
  environment:
     KAFKA_BROKER_ID: 3
     KAFKA_ADVERTISED_PORT: "9092"
  volumes:
    - /kafka_3:/kafka